name: "CI"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fmt:
    uses: ./.github/workflows/fmt.yml

  lint:
    uses: ./.github/workflows/lint.yml

  flake-check:
    uses: ./.github/workflows/flake-check.yml

  build:
    needs: [fmt, lint, flake-check]
    uses: ./.github/workflows/build.yml
